apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-deployment
  labels: 
    app: survey
    author: baalavignesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey
  template:
    metadata:
      labels:
        app: survey
    spec:
      containers:
      - name: survey-pod
        image: baalavignesh21/baalavignesh-survey
        ports:
        - containerPort: 80
